### ISSUE TITLE
MORichNotification Rich Notification are not showing 

### ISSUE THREAD

**Issue by anugrah-sebastian** [moengage/MORichNotification#2]
Hi I have integrated the MORichNotification into my project and followed all the steps in the document.But when I trigger the image notification,. image won't show in the notification.I have downloaded the demo  project in the document and followed the same rules.

**Comment by anugrah-sebastian** [comment]
@ChengappaMoEngage what should i do to get the Rich Notifications from Moengage as I have followed all the steps in the MoRich Push Notifications docs.Do I need to do anything else besides document.

**Comment by anugrah-sebastian** [comment]
@ChengappaMoEngage hey I got the image. I receive notifications from firebase also so in that case what should I do?

**Comment by ChengappaMoEngage** [comment]
Hey @anugrah-sebastian, `MORichNotification` is a module that is built to support only notifications from the `MoEngage` platform. Unfortunately for campaigns that you will be creating from firebase console, you will have to do the handling separately on your own.

Since you were able to get the image I'm closing this issue.
